application:
  name: ${PROJECT_NAME}
  timezone: ${USER_TIMEZONE:America/Sao_Paulo}

server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aeon_db
    username: aeon
    password: aeon

  jpa:
    show-sql: false #true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dll-auto: validate
        use-new-id-generator-mappings: false
      generate-ddl: false
  liquibase:
    changeLog: classpath:db/changelog/db.changelog-master.yml