version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: customer_registrator_database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: aeon
      MYSQL_PASSWORD: aeon
      MYSQL_DATABASE: aeon_db
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - c:/volumes/customer_registrator:/var/lib/mysql